stock_market_acronyms = {
    'NYSE': 'New York Stock Exchange (NYSE)',
    'NASDAQ': 'National Association of Securities Dealers Automated Quotations (NASDAQ)',
    'LSE': 'London Stock Exchange (LSE)',
    'JPX': 'Japan Exchange Group (JPX)',
    'SSE': 'Shanghai Stock Exchange (SSE)',
    'HKEX': 'Hong Kong Exchanges and Clearing (HKEX)',
    'Euronext': 'Pan-European Exchange (Euronext)',
    'TSX': 'Toronto Stock Exchange (TSX)',
    'BSE': 'Bombay Stock Exchange (BSE)',
    'NSE': 'National Stock Exchange of India (NSE)',
    'ASX': 'Australian Securities Exchange (ASX)',
    'FWB': 'Frankfurt Stock Exchange (FWB)',
    'JSE': 'Johannesburg Stock Exchange (JSE)',
    'BM&F Bovespa': 'São Paulo Stock Exchange (BM&F Bovespa)',
    'KRX': 'Korea Exchange (KRX)',
    'TWSE': 'Taiwan Stock Exchange (TWSE)',
    'SIX': 'Swiss Exchange (SIX)',
    'BME': 'Bolsas y Mercados Españoles (BME)',
    'MOEX': 'Moscow Exchange (MOEX)',
    'TASE': 'Tel Aviv Stock Exchange (TASE)',
    'SGX': 'Singapore Exchange (SGX)',
    'BIST': 'Borsa İstanbul (BIST)',
    'DFM': 'Dubai Financial Market (DFM)',
    'ADX': 'Abu Dhabi Securities Exchange (ADX)',
    'Bursa Malaysia': 'Malaysian Stock Exchange (Bursa Malaysia)',
    'NZX': 'New Zealand Exchange (NZX)',
    'BMV': 'Mexican Stock Exchange (BMV)',
    'OSE': 'Oslo Stock Exchange (OSE)',
    'CSE': 'Colombo Stock Exchange (CSE)',
    'PSE': 'Philippine Stock Exchange (PSE)'
}