acronyms = {
    'afaik': 'as far as I know',
    'idk': 'I don\'t know',
    'imho': 'in my humble opinion',
    'lol': 'laugh out loud',
    'tbh': 'to be honest',
    'tldr': 'too long; didn\'t read',
    'fyi': 'for your information',
    'brb': 'be right back',
    'btw': 'by the way',
    'lmao': 'laughing my ass off',
    'omg': 'oh my god',
    'smh': 'shaking my head',
    'rofl': 'rolling on the floor laughing',
    'np': 'no problem',
    'ama': 'ask me anything',
    'irl': 'in real life',
    'nsfw': 'not safe for work',
    'nvm': 'never mind',
    'afk': 'away from keyboard',
    'bbl': 'be back later',
    'jk': 'just kidding',
    'imo': 'in my opinion',
    'ty': 'thank you',
    'thx': 'thanks',
    'wtf': 'what the fuck',
    'ftw': 'for the win',
    'gg': 'good game',
    'gr8': 'great',
    'b4': 'before',
    'atm': 'at the moment',
    'bff': 'best friends forever',
    'faq': 'frequently asked questions',
    'icymi': 'in case you missed it',
    'yolo': 'you only live once',
    'eli5': 'explain like I\'m 5',
    'iirc': 'if I recall correctly',
    'itap': 'I took a picture',
    'mfw': 'my face when',
    'mrw': 'my reaction when',
    'pov': 'point of view',
    'psa': 'public service announcement',
    'til': 'today I learned',
    'daae': 'does anybody else agree',
    'fomo': 'fear of missing out',
    'ftl': 'for the loss',
    'hmb': 'hold my beer',
    'ianal': 'I am not a lawyer',
    'iama': 'I am a',
    'imo': 'in my opinion',
    'iirc': 'if I recall correctly',
    'irl': 'in real life',
    'iso': 'in search of',
    'mfw': 'my face when',
    'mrw': 'my reaction when',
    'op': 'original poster',
    'psa': 'public service announcement',
    'qft': 'quoted for truth',
    'sfw': 'safe for work',
    'stfu': 'shut the fuck up',
    'tia': 'thanks in advance',
    'til': 'today I learned',
    'ysk': 'you should know'
}

